global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: url-shortener
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - url-shortener:8080