version: '3.1'

services:
  url-shortener:
    image: urlshortener:latest
    command: ['--db.host=mydb']
    depends_on:
      mydb:
        condition: service_started
    networks:
      - url-shortener-network
    ports:
      - '8080:8080'
    environment:
      spring.datasource.url: jdbc:mysql://mydb:3306/urlShortener?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      spring.datasource.password: 'password'

  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    container_name: mydb
    networks:
      - url-shortener-network

networks:
  url-shortener-network:

