version: '3.1'

services:
  url-shortener:
    image: urlshortener:latest
    command: ['--db.host=mydb']
    depends_on:
      mydb:
        condition: service_started
    networks:
      - url-shortener-network
    ports:
      - '8080:8080'
    environment:
      spring.datasource.url: jdbc:mysql://mydb:3306/urlShortener?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      spring.datasource.password: 'password'

  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    container_name: mydb
    networks:
      - url-shortener-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - url-shortener-network

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge

